package com.jazasoft.mtdb.test;

import com.jazasoft.mtdb.TenantCreatedEvent;
import com.jazasoft.mtdb.entity.Company;
import com.jazasoft.mtdb.repository.CompanyRepository;
import com.jazasoft.mtdb.service.IConfigurationService;
import com.jazasoft.mtdb.tenant.IMultiTenantConnectionProvider;
import com.jazasoft.mtdb.util.Utils;
import com.jazasoft.util.YamlUtils;
import org.hibernate.engine.jdbc.connections.spi.AbstractDataSourceBasedMultiTenantConnectionProviderImpl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationListener;
import org.springframework.context.annotation.Profile;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.init.DatabasePopulatorUtils;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import javax.annotation.PostConstruct;
import javax.sql.DataSource;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * Created by mdzahidraza on 26/06/17.
 */

@Component
@Scope( proxyMode = ScopedProxyMode.TARGET_CLASS)
@Transactional(value="masterTransactionManager", readOnly = true)
@Profile("test")
public class MultiTenantConnectionProviderImplTest extends AbstractDataSourceBasedMultiTenantConnectionProviderImpl implements IMultiTenantConnectionProvider, ApplicationListener<TenantCreatedEvent>{

    private static final long serialVersionUID = 6246085840652870138L;

    private final static Logger LOGGER = LoggerFactory.getLogger(MultiTenantConnectionProviderImplTest.class);

    private Map<String, DataSource> map; // map holds the companyKey => DataSource

    private String defaultTenant;

    @Autowired
    private CompanyRepository companyRepository;

    @Autowired
    private IConfigurationService configurationService;

    @Value("${spring.datasource.url}")
    private String url;

    @Value("${spring.datasource.driverClassName}")
    private String dataSourceClassName;

    @Value("${spring.datasource.username}")
    private String user;

    @Value("${spring.datasource.password}")
    private String password;

    @Value("${spring.datasource.platform}")
    private String platform;

    @Autowired
    private DataSource dataSource; // injected here to get properties and to provide default.

    @PostConstruct
    public void load() {
        map = new HashMap<>();
        init();
    }

    public void init() {
        for (Company company : companyRepository.findAll()) {
            // in this experiment we are just using one instance of mysql. URL is generated by replacing master database
            // name with company key to get new database URL
            try {
                addDatasource(company.getDbName());
                initDefaultConfiguration(company.getDbName());
            } catch (Exception e) {
                LOGGER.error("Error in database URL {}", url, e);
            }
        }
    }

    @Override
    protected DataSource selectAnyDataSource() {
        LOGGER.debug("######### Selecting any content source");
        return dataSource;
    }

    @Override
    protected DataSource selectDataSource(String tenantIdentifier) {
        DataSource result;
        if (defaultTenant != null && map.containsKey(defaultTenant)) {
            result = map.get(defaultTenant);
            //defaultTenant = null;
            return result;
        } else {
            result = map.containsKey(tenantIdentifier) ? map.get(tenantIdentifier) : dataSource;
        }
        return result;
    }

    @Override
    public void onApplicationEvent(TenantCreatedEvent event) {
        String dbName = event.getDbName();
        addDatasource(dbName);
        initDefaultConfiguration(dbName);
    }

    @Override
    public void setTenantIdentifier(String tenantIdentifier) {
        LOGGER.debug("setTenantIdentifier: tenant = {}", tenantIdentifier);
        this.defaultTenant = tenantIdentifier;
    }

    private void addDatasource(String tenantIdentifier) {
        LOGGER.debug("addDatasource");
        DataSource dataSource = getDatasource(tenantIdentifier);
        map.put(tenantIdentifier, dataSource);
        initDb(dataSource);
    }

    private DataSource getDatasource(String tenantId) {
        String newUrl = url.replace("tnt_db_master", tenantId);
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName(dataSourceClassName);
        dataSource.setUrl(newUrl);
        dataSource.setUsername(user);
        dataSource.setPassword(password);
        return dataSource;
    }


    private void initDb(DataSource dataSource) {
        LOGGER.info("initDb");
        Resource resource = new ClassPathResource("h2-schema.sql");
        ResourceDatabasePopulator populator = new ResourceDatabasePopulator();
        populator.addScript(resource);
        populator.setContinueOnError(false);
        DatabasePopulatorUtils.execute(populator , dataSource);
    }

    private void initDefaultConfiguration(String tenant) {
        String filename = Utils.getAppHome() + File.separator + "conf" + File.separator + tenant + ".yml";
        File file = new File(filename);
        if (file.exists()) return;
        LOGGER.info("Initializing default configuration. config file = {}", filename);
        try {
            YamlUtils.getInstance().writeProperties(file, configurationService.getDefaultConfiguration());
        } catch (IOException e) {
            LOGGER.error("Error occured initializing Default configuration. {}", e.getMessage());
        }
    }

}


